### ISSUE TITLE
update debian packages?

### ISSUE THREAD

**Issue by genofire** [n0emis/ansible-role-bigbluebutton#20]
Hi,
do we like to update the system with the role?
Or just install BigBlueButton.

So we need to change from `present` to `latest` in several places like:

https://github.com/n0emis/ansible-role-bigbluebutton/blob/ae0e9b651c19a54fe477f22676282f39921999c5/tasks/main.yml#L19

https://github.com/n0emis/ansible-role-bigbluebutton/blob/ae0e9b651c19a54fe477f22676282f39921999c5/tasks/main.yml#L69

**Comment by syhe** [comment]
I think the status quo is fine, since I wouldn't want the role to update BBB to a new version when I'm trying to apply an unrelated configuration change.

I could also live with a pinned version, so we get a somewhat reproducible state, but that would entail a lot more work in maintaining this role.

**Comment by DO1JLR** [comment]
I like the status quo too.

To update bbb with this role there could be a new variable to choose between ``state: present`` and ``state: latest``. But **the default option should be ``state: present``!**

**Comment by n0emis** [comment]
> So we need to change from present to latest in several places

I would say: it would be a great addition, if there was a config-variable that would enable the user to update.
