### ISSUE TITLE
Does not deploy turn-stun-servers.xml when external stun/turn is set and bbb_turn_enable is false

### ISSUE THREAD

**Issue by BrutalBirdie** [n0emis/ansible-role-bigbluebutton#70]
When using an external Stun/Turn Server and not install coturn via `bbb_turn_enable: false` the `turn-stun-servers.xml` will not be deployed.
This will result in error 1007 in certain networks which need a turn.

My personal hotfix was to simply remove all check in the jinja template for bbb_turn_enable, but this is a bad hotfix imo.

If there is no local coturn and no external stun/turn is defined that don't deploy.

Maybe another extra var like `bbb_external_coturn: false` as default which then is checked in the jinja template?

Resulting into something like:

```
 {% if bbb_turn_enable or bbb_external_coturn %} 
```

Looking forward for your opinion.

https://github.com/n0emis/ansible-role-bigbluebutton/blob/b8cdb5578de4e0c64956033a7b31b1d0b3ca5ebd/templates/bbb/turn-stun-servers.xml.j2#L26

**Comment by n0emis** [comment]
There are two variables to enable/disable turn-server things:
* `bbb_coturn_enable` to install (or not install) a local turn-server
* `bbb_turn_enable` to enable/disable the use of turn server in general

Therefor `bbb_turn_enable` has the same meaning as your proposed `bbb_external_coturn`. If I understand you usecase correctly u should set these variables as following:
```
bbb_coturn_enable: no
bbb_turn_enable: yes
bbb_turn_servers:

```

Please correct me if I understood you question wrong, otherwise I will close this issue in a few days.

**Comment by BrutalBirdie** [comment]
You are completely right!
I just looked at the wrong variable for too long.

`bbb_turn_enable` does exactly what I proposed, I just looked at `bbb_coturn_enable` and the code using this variable which installs the local coturn and `bbb_turn_enable` is only being used in `n0emis.bigbluebutton/templates/bbb/turn-stun-servers.xml.j2`

Sorry for that. I will close this Issue again.
